on:
    schedule:
        - cron: "0 8 * * *"

jobs: 
    daily_task:
        runs-on: ubuntu-latest
        steps:
            - name: print message
              run: echo "Running the scheduled task"